site_name: orangoplan 
site_url: https://danieljansenh.github.io/OrangoPlan/
copyright: Copyright © 2026 Daniel Harianto


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - search.disabled
    - search.highlight
    - content.code.copy
    - content.code.select

  font:
    text: Work Sans
  logo: assets/Logo.png
  favicon: assets/Logo.png

# Palette example (commented out):
# palette: 
#   - scheme: default
#     toggle:
#       icon: material/brightness-7 
#       name: Switch to dark mode
#   - scheme: slate
#     toggle:
#       icon: material/brightness-4
#       name: Switch to light mode  

# plugins:
#   - search

nav:
  - Home:
    - index.md
    - Getting Started: Home/Getting_Started.md
    - References: Home/References.md
  - Analysis: Wrk_Features/Analysis.md
  - Design: Wrk_Features/Design.md
  - Utility: Wrk_Features/Utility.md
  - Table: Wrk_Features/Table.md
  - About: Authorship.md

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/danieljharianto
